records/urls.py
from django.urls import path
from . import views

app_name = 'records'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('submit', views.submit, name='submit'),
]

say_something/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('records.urls')),
]

records/models.py
from django.db import models


class Record(models.Model):
    text = models.CharField(max_length=100)
    publication_date = models.DateTimeField()

    def __str__(self):
        return self.text

records/views.py
from django.shortcuts import render
from django.views import generic 
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.utils import timezone

from .models import Record


class IndexView(generic.ListView):
    template_name = 'records/index.html'

    def get_queryset(self):
        return Record.objects.order_by('-publication_date')[:5]


def submit(request):
    try:
        record_text = request.POST['record']
        
        if record_text == '':
            raise KeyError()

    except KeyError:
        record_list = Record.objects.order_by('-publication_date')[:5]
        context = { 
            'error_message': 'Write something before submit!',
            'record_list': record_list
        }
        
        return render(request, 'records/index.html', context)
    
    else:
        record = Record(text=record_text, publication_date=timezone.now())
        record.save()

        return HttpResponseRedirect(reverse('records:index'))

records/templates/records/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'records/css/style.css' %}">

    <title>Say Something</title>
</head>
<body>
    
    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
</html>

records/templates/records/index.html
{% extends 'records/base.html' %}

{% block content %}
    <div class="jumbotron vertical-center">
        <div class="container text-center">
            <div class="row block">
                <h3 class="header">Say something</h3>
                <small id="subtitle" class="form-text text-muted subtitle">...to someone.</small>
            </div>
            
            <div class="row justify-content-md-center">
                <form class="form-inline" action="{% url 'records:submit' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" name="record" id="record" placeholder="Type here...">
                    </div>
    
                    <button type="submit" class="btn btn-primary submit-button">Submit</button>
                </form>
            </div>

            <div class="row">
                <div class="col"></div>
                <div class="list-group justify-content-md-center col-6 record-list">
                    {% if error_message %} <p class="red">{{ error_message }}</p> {% endif %}
                    
                    {% if record_list %}
                        {% for record in record_list %}
                            <a href="#" class="list-group-item list-group-item-action">{{ record.text }}</a>                
                        {% endfor %}
                    {% else %}
                         <small id="subtitle" class="form-text text-muted subtitle">Nothing was said.</small>
                    {% endif %}

                </div>
                <div class="col"></div>                
            </div>
        </div>
    </div>
{% endblock  %}